import test from 'node:test';import assert from 'node:assert/strict';
import {foundationFixture} from './fixtures/build-course.mjs';import {validateBuildPath} from './build-path.mjs';
let api={};try{api=await import('../assets/build-progress.mjs')}catch{}
function setup(){assert.equal(typeof api.emptyProgress,'function','progress API exists');const f=foundationFixture();const course=validateBuildPath(f.raw,f.lessons,f.referenceData);return {course,state:api.emptyProgress(course)}}
const report={status:'passed',source:'learner-report',note:'Explained it',reportedAt:'2026-09-28T12:00:00.000Z',courseRevision:'course-1',sourceSnapshotId:'snapshot-1',needsReview:false};
test('viewing and trying never record a passed check',()=>{let {course,state}=setup();state=api.reduceProgress(state,{type:'visit',stepId:'m00-start-build'},course);state=api.reduceProgress(state,{type:'attempt',stepId:'m00-start-build'},course);assert.equal(state.workspaces.practice.position,'m00-start-build');assert.equal(state.workspaces.practice.attempts['m00-start-build'],1);assert.deepEqual(state.workspaces.practice.reports,{})});
test('practice result stays separate when a team profile is selected',()=>{let {course,state}=setup();state=api.reduceProgress(state,{type:'report',checkId:'m00-start-check',report},course);state=api.reduceProgress(state,{type:'profile',profile:{id:'team-a',kind:'team',root:'/tmp/team',mappings:[]}},course);state=api.reduceProgress(state,{type:'workspace',id:'team-a'},course);assert.deepEqual(state.workspaces['team-a'].reports,{});assert.equal(state.workspaces.practice.reports['m00-start-check'].status,'passed')});
test('import retains notes but marks every imported result for review',()=>{let {course,state}=setup();state=api.reduceProgress(state,{type:'report',checkId:'m00-start-check',report},course);state=api.reduceProgress(state,{type:'note',stepId:'m00-start-build',text:'<img src=x onerror=alert(1)>'},course);const imported=api.importProgress(api.exportProgress(state),course);assert.equal(imported.workspaces.practice.notes['m00-start-build'],'<img src=x onerror=alert(1)>');assert.equal(imported.workspaces.practice.reports['m00-start-check'].source,'import');assert.equal(imported.workspaces.practice.reports['m00-start-check'].needsReview,true)});
test('a changed course retains history and requests another check',()=>{let {course,state}=setup();state=api.reduceProgress(state,{type:'report',checkId:'m00-start-check',report},course);course.path.revision='course-2';const read=api.readProgress({getItem:()=>JSON.stringify(state)},course);assert.equal(read.state.workspaces.practice.reports['m00-start-check'].needsReview,true)});
test('denied storage is a warning with usable in-session state',()=>{const {course,state}=setup();assert.match(api.readProgress({getItem(){throw Error('denied')}},course).warning,/unavailable/i);assert.equal(api.saveProgress({setItem(){throw Error('quota')}},state),false)});
test('corrupt storage is not overwritten or mistaken for success',()=>{const {course}=setup();let writes=0;const result=api.readProgress({getItem:()=>'{broken',setItem:()=>writes++},course);assert.match(result.warning,/corrupt/i);assert.equal(writes,0);assert.deepEqual(result.state.workspaces.practice.reports,{})});
for(const [name,mutate] of [['version',s=>s.version=9],['unknown step',s=>s.workspaces.practice.position='removed'],['invalid report',s=>s.workspaces.practice.reports['m00-start-check']={...report,status:'mastered'}],['invalid date',s=>s.workspaces.practice.reports['m00-start-check']={...report,reportedAt:'bad'}],['unknown check',s=>s.workspaces.practice.reports.removed=report],['negative attempts',s=>s.workspaces.practice.attempts['m00-start-build']=-1]])test(`import rejects ${name}`,()=>{const {course,state}=setup();mutate(state);assert.throws(()=>api.importProgress(JSON.stringify(state),course))});
test('rejects oversized and prototype keys',()=>{const {course}=setup();assert.throws(()=>api.importProgress(' '.repeat(1000001),course),/large/);assert.throws(()=>api.importProgress('{"__proto__":{}}',course),/key/)});
test('legacy activity key is not read or rewritten',()=>{const {course}=setup();const keys=[];api.readProgress({getItem:key=>{keys.push(key);return null}},course);assert.deepEqual(keys,['code-arena-learning:build:v1'])});
